title: "HackTheBox Writeups"
description: "Documenting my OSCP journey through machines on HackTheBox, without Metasploit."
url: "https://jonathan-corbin.github.io"

remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

# Basic site info
author: Jonathan Corbin
email: 

# Optional links (these show up in header/footer)
footer: "Follow yourself"
social_links:


# Posts per page
paginate: 10
